services:
  - type: web
    name: football-tracking-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.0
